### ISSUE TITLE
Mass on element and total mass

### ISSUE THREAD

**Issue by gaetanocmr** [volkanozsarac/ModalAnalysis-OpenSeespy#1]
Hi, 
thanks for your nice tool, I really appreciated it.
I would like to ask if you checked the tosal mass when mass on element is used. I found a little difference between Sap2000 and your code.
have a nice day

**Comment by volkanozsarac** [comment]
Hey, 
@gaetanocmr thank you for your comment. I remember checking the modal masses and total mass with seismostruct for all test structures, since the modal masses were given as output directly by the software. Yet, I have not checked them using SAP2000. I will have a look at it, and try to see what is the problem.

**Comment by gaetanocmr** [comment]
Thanks for your fast answer.
Maybe I got something wrong on my code, I will check it.
I'll keep you posted

**Comment by volkanozsarac** [comment]
@gaetanocmr, you are right, I have realized that I messed up with units in SAP2000 model. The verification of the example is fine for Seismostruct, I uploaded the correct model for SAP2000. Thank you! 
Apparently, I have entered the mass and youngs modulus 10 times bigger than what they should be in the model, that is why everything was the same but the joint masses were 10 times greater. 

Also, note that ModalAnalysis.py will output the total mass obtained from unrestrained part of the global mass matrix. In other words, if a node is fixed in certain DOF, the masses assigned to this DOF will not be considered in calculations of total mass. I may change this feature later to consider also masses assigned to restrained DOFs, depending on user requests.

Please let me know if you think there is still a problem.
Cheers

**Comment by gaetanocmr** [comment]
@volkanozsarac you're welcome :). 
I give in my model masses on the element and not at the node, and I found that I have a little differences between mass calculated by Sap2000 and the ones on OpsPy with your code.
As result I obtain in Sap2000 (the right one) 35.33 [kNs^2/m], from your code 33.06 [kNs^2/m].
I will check my model again, cause your script and my calculation give the same period, frequency, ecc. so they are calculated with same mass matrix and total mass, maybe I do something wrong.
Cheers

**Comment by volkanozsarac** [comment]
I am not sure, but I checked the models for Bridge3d example in which I have used distributed masses.
From all 3 models, I obtain the same total mass values for the unrestrained mass matrix which is used to calculate modal properties essentially:
Mx    |My     |Mz     [kN.s2/m]
3696 | 2896 | 2896

I uploaded the SAP2000 output as excel file.

**Comment by gaetanocmr** [comment]
Thanks, maybe the problem is somewhere in my code then, I will check it closely, we'll see what I got.
I will close the issue then, it's seems there isn't in this case.
I'll have a look at your example folder, and thanks for the upload.
keep in touch.
